"""empty message

Revision ID: 4310d6bb6664
Revises: 198b0eebcf9
Create Date: 2015-09-12 20:54:43.259030

"""

# revision identifiers, used by Alembic.
revision = '4310d6bb6664'
down_revision = '198b0eebcf9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namealarme', sa.String(length=120), nullable=True),
    sa.Column('startdate', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=140), nullable=True),
    sa.Column('frequence', sa.String(length=140), nullable=True),
    sa.Column('days', sa.String(length=140), nullable=True),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'users', 'music_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('music_id', sa.INTEGER(), nullable=True))
    op.drop_table('alarm')
    ### end Alembic commands ###
